# fly.toml app configuration file generated for ib-predictor on 2024-10-10T02:49:30+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ib-predictor'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  # The release_command is not needed for a continuous-running Flask app.
  # It is safe to remove this line.

[env]
  NODE_OPTIONS = '--max-old-space-size=4096'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
